version: "3.7"

services:
  web:
    container_name: nginx-laravue
    image: nginx:alpine
    ports:
      - "8098:80"
    volumes:
      - type: bind
        source: ./
        target: /var/www
        consistency: cached
      - ./docker/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravue
    restart: always
  phpfpm:
    container_name: php-fpm-laravue
    build:
      context: ./docker
      dockerfile: php.dockerfile
    volumes:
      - type: bind
        source: ./
        target: /var/www
        consistency: cached
      - ./tmp/grinds:/tmp/grinds
    networks:
      - laravue
    working_dir: /var/www
    restart: always

networks:
  laravue:
